Repository Elzian-Agro/Dev-Blog-Site, pull requests merged in 2022-07, with the labels that each got.

#6 Development branch
  img/Java.jpg
  img/PIUDP.jpg
  img/iot.jpeg
  img/iot.jpg
  img/iot2.jpg
  img/sql.jpg
  img/sql.png
  img/thejani.jpg
  index.html
  scripts.js
  styles.css
Labels: help wanted

#8 Development branch
  index.html
Labels: help wanted

#9 Added the files
  css/styles.css
  img/Abuvarana.jpeg
  img/Agile.jpg
  img/Elzian.png
  img/Elzian_logo.png
  img/Elzian_logo2.png
  img/GitHub-Mark.png
  img/Interns.jpg
  img/Java.png
  img/Sujina.jpeg
  img/Thejani.jpeg
  img/full_logo.png
  img/hightech-earth-network-world-wallpaper-preview.jpg
  img/intern.jpg
  img/iot.png
  img/iot2.png
  img/java 2.png
  img/logo.png
  img/logo.svg
  img/logo1.png
  img/piumal.jpeg
  img/razeen.jpg
  img/sql.jpg
  img/sql2.jpg
  img/team.png
  index.html
  js/scripts.js
Labels: enhancement

#14 Alignment Updated
  css/styles.css
  img/neranjan.jpg
  index.html
Labels: enhancement

#16 Background color updated
  css/styles.css
  index.html
Labels: enhancement

#25 Logo issue fixed
  .vscode/launch.json
  assets/img/about/5.jpeg
  css/styles.css
  img/IOTsensor.webp
  img/blockchain.jpg
  img/css.png
  img/python3.png
  img/training.jpg
  index.html
Labels: enhancement

#31 Footer updated.
  index.html
Labels: bug, enhancement

#32 Added Thenuka's Image and Details
  assets/img/portfolio/all.PNG
  assets/img/portfolio/css.jpg
  assets/img/portfolio/html.jpg
  assets/img/portfolio/j.png
  assets/img/portfolio/jq.png
  css/styles.css
  img/IOT agriculture.jpg
  img/Thenuka.jpg
  img/blockchain.jpg
  img/blockchain2.jpg
  img/css.jpg
  img/eth.png
  img/eths.jpg
  img/python-neranjan.jpg
  img/python-programming.jpg
  index.html
Labels: bug, enhancement

#40 Remove sql in the footer
  css/header-bubble-style.css
  css/styles.css
  img/elzian_agro-bg.png
  img/mernStack_blog.jpg
  img/mern_layers.PNG
  img/mern_logo.png
  img/ramesh.jpg
  index.html
Labels: bug

#49 Created a new blog about MongoDB
  css/styles.css
  img/AI_Complete_Graph.jpeg
  img/Semini.jpg
  img/logo-mongodb.jpg
  img/mongo-img1.jpg
  img/mongo-img3.png
  img/mongo-img4.png
  img/mongo-img5.png
  img/mongodb-img2.jpg
  index.html
Labels: enhancement

#50 Changed text-align property in MongoDB Blog
  css/styles.css
  img/MERN_blog.png
  img/UI_UX 2.png
  img/UI_UX.png
  img/himaya.jpg
  img/logo_Elzian.png
  index.html
  js/scripts.js
Labels: enhancement

#51 Updated the blog card design
  css/styles.css
  img/Blockchain.png
  img/IoT (2).png
  img/SQL.png
  img/java-logo.png
  img/mongoDB1.png
  img/python.png
  img/web.png
  index.html
Labels: enhancement

#52 Update the UI/UX blog
  css/styles.css
  img/UI_UX(1).png
  img/UI_UX(2).PNG
  img/UI_UX(3).PNG
  index.html
Labels: enhancement

#53 Added tools used for UI/UX blog
  css/styles.css
  img/UI_UX/Framer X.png
  img/UI_UX/Framer.png
  img/UI_UX/Invision_Studio.png
  img/UI_UX/Xd.png
  img/UI_UX/axure.png
  img/UI_UX/craft.png
  img/UI_UX/figma.png
  img/UI_UX/marvel.png
  img/UI_UX/sketch.png
  index.html
Labels: enhancement

#58 Add files via upload
  img/mathy.jpeg
  index.html
Labels: enhancement
